### ISSUE TITLE
Improve repo details

### ISSUE THREAD

**Issue by angelofallars** [axyl-os/axyl-iso#10]
The download for Axyl is in this repo itself, `axyl-iso`. Therefore, the repo description should be a bit more descriptive.

I suggest this as the description:

`Axyl is a Linux distro centered on tiling window managers. Choose from i3, bspwm, dwm and more.`

The website field should of course link to the website, `https://axyl-os.github.io/` .

When the repo details are edited, it should look like this:

![image](https://user-images.githubusercontent.com/39676098/141435050-30023f43-b839-494c-a915-2155bda79c68.png)

**Comment by Kungger-git** [comment]
Thanks! @angelofallars will do that.
