### ISSUE TITLE
Axyl system settings don't change

### ISSUE THREAD

**Issue by geckobob** [axyl-os/axyl-iso#100]
So far (2nd day), Axyl looks pretty good. After another arch distro, which is way over loaded, this is a breath of fresh air. Enjoying Qtile.
However, I'm having problems making system changes. The system, as delivered, uses xfce4 system utilities. I have tried to change the display settings: changing the primary display to the other monitor. No deal on that one. Then, attempting to change Appearance settings also gets no deal. Just wanting to change from light to dark system style gets no change. Not sure in writing this if more system info is needed to help find a solution. I'm here if needed. Thanks

**Comment by lknows** [comment]
Have you seen the wiki on my fork?: https://github.com/lknows/axyl-iso/wiki

**Comment by Peppe61** [comment]
Hi @geckobob : at least for the appearance you'll have to use lxappearance (installed already). Theming in Xfce settings and in lxappearance needs to be in sync to have a consistent look and feel. Have fun😊

**Comment by geckobob** [comment]
Not quite sure if this is a reply to Peppe61, since I'm inexperienced in posting here on github, but if it is a reply, thanx for the tip. I put an xrandr command in autostart.sh and that solved that problem. Still yet to get to the other. Sometime today maybe. Thanx again.

**Comment by Peppe61** [comment]
Great to hear it is working at least partially for now. The message reached me indeed :-)

Aug 21, 2022 04:59:49 geckobob ***@***.***>:
