### ISSUE TITLE
Update key bindings information to show i3 bindings, since they're non-default

### ISSUE THREAD

**Issue by nickadair-work** [axyl-os/axyl-iso#103]
It took me a while to figure out why the key bindings in the i3 user guide (https://i3wm.org/docs/userguide.html) weren't working, particularly the split-horizontal binding. Turns out the default Axyl i3 configuration changes that binding from mod-h to mod-b, however, this isn't mentioned any where that I can find, and there's no i3 specific information listed at all on the key bindings information page, even though it's the default window manager.

**Comment by lknows** [comment]
It is a bit embarrassing not having a more specific i3 listing on the keybindings.md file.
I have updated it and made multiple disclaimers on the wiki pages to make sure the swap is well communicated to new users. Thank you for identifying this small flip of keybinds, I think this satisfies closing requirements, yes?

**Comment by nickadair-work** [comment]
Awesome, thanks very much for updating that! Yes, this looks close-able now.
