### ISSUE TITLE
Issue with reusing user accounts from previous linux install, skel files don't get copied across

### ISSUE THREAD

**Issue by Thermatix** [axyl-os/axyl-iso#104]
I had wanted to re-use the same user account I had been using with Regolith Linux, I had decided to distro hop from it and chose axyl.

Since I keep my home on its own labelled partition so changing the distro is relatively simple. 
However, there were two issues with this when I installed axyl:

* it wiped out all of my dotfiles in my home directory, fortunately I keep my dotfiles in a separate dir so only the symlinks got wiped
  Though it did get my .ssh folder so all my keys are gone :(
* It didn't create the skel config files needed so I got a blank desktop when I logged in

I tried copying files across from root (wasn't aware of the skel folder at the time) but It was lacking something.

To fix this I renamed my old home dir and reinstalled again and now it's all working.

The installer should be smart enough to realise you're re-using an old home directory and instead of wiping clean, create copies in the home dir (like .zshrc_axyl_default) or provide a method during install/first login to fix.

**Comment by lknows** [comment]
This certainly needs fixing, but also seems far from easy to resolve. I will probably need someone else's assistance creating a solution around this specific problem.
