### ISSUE TITLE
ERROR on ipw2100-fw and ipw2200-fw not found when Archiso build.sh script is run on axyl-iso

### ISSUE THREAD

**Issue by D3vil0p3r** [axyl-os/axyl-iso#106]
Hello,
I cloned `axyl-iso` repo for testing, and, when I run the installation script `build.sh` or `re-build.sh` for creating an ISO by Archiso, I get an error that says `ipw2100-fw` and `ipw2200-fw` are not found.

Can you please remove these two packages from `packages.x86_64` file if they are not available anymore?

To reproduce:
1. `git clone https://github.com/axyl-os/axyl-iso`
2. `cd axyl-iso/installation-scripts`
3. `./re-build.sh`

**Comment by lknows** [comment]
Big thanks for pointing this out. I see no reason otherwise, so I've already committed the changes.
