### ISSUE TITLE
Qtile not installing with os

### ISSUE THREAD

**Issue by Avery20** [axyl-os/axyl-iso#112]
I have tried multiple times and the installation will not install qtile, as a temporary fix I will install with i3 but why this should not be the solution. there also does not seem to be a way to choose multiple Wm's on install which makes a problem like this more of a deterrent to new users. Thanks for your time

**Comment by cyberguy2017** [comment]
I am also experiencing the same issue, it acts like it install then at the login screen there is no option for qtile or anything,I hope they fix this issue right away this is annoying to say the least

**Comment by danifersonaglia** [comment]
the same issue for me

**Comment by karolstaniek91** [comment]
I'm facing the same issue. Did anyone found any solution?

**Comment by wulfalpha** [comment]
I was able to get qtile installed with no configuration by  doing sudo Paxman -Syu and then sudo Paxman -S axyl-qtile. Not sure where to get the configuration from tho
