### ISSUE TITLE
ISO axyl-2022.08.10-x86_64 not booting

### ISSUE THREAD

**Issue by Bastkapp** [axyl-os/axyl-iso#113]
When I try to boot from the bootstick with the axyl-2022.08.10-x86_64.iso, my screen turns black for a second and then goes back to my BIOS.

I am using a Thinkpad E14 gen 3 and trying to boot with a Windows bootstick works perfectly fine.

**Comment by Mason-17** [comment]
I know this is several months old (lol), but try using a different usb @Bastkapp

**Comment by Deiabsons** [comment]
Is this project (axyl) still alive.
When install iso fails.

**Comment by Mason-17** [comment]
The project isn't really being worked on atm. if we want it alive, we as fans have to do it ourselves.
