### ISSUE TITLE
i3 Config Super Key Change

### ISSUE THREAD

**Issue by JOTASatellite** [axyl-os/axyl-iso#118]
hi, I've changed around the $mod and $alt keys in the i3 config file as I want the super key to be Left Alt, and $alt to be Win Key.

This worked, mostly, but the keybindings that are displayed in the conky cheatsheet are still hard coded somewhere else, so I cant SuperKey with the left alt key when using those commands.

Where can this configuration be changed?

**Comment by theolodger** [comment]
Hello, the configuration file you are looking for should be at ~/.config/sxhkd/sxkhdrc, I believe. It does still contain bspwm keybindings, for some unknown (to me) reason.
