### ISSUE TITLE
[Question] Multiple Monitor Support

### ISSUE THREAD

**Issue by UpperCenter** [axyl-os/axyl-iso#12]
I recently installed Axyl on my main PC, but am having some issues with my display setup.
I have three monitors, one is 1440p and the other two are 1080p.
When using bspwm, only my middle (1440p) monitor displays content, the other two are totally black. How can I fix this so all monitors are detected in the correct order?

Also, how do I get polybar to display on all monitors?

Finally, is there a way to change how window spawning works? For example sometimes I want Thunar to open in the same workspace as Firefox.

**Comment by Shinyzenith** [comment]
For display configuration you can use `arandr` , install it with `sudo pacman -S arandr --noconfirm --needed`.
Arrange your displays in the GUI and then click on the save button, and then just source the script in your BSPWMRC, and it will work.


For polybar, we'll have to wait for Gabriel, I have no idea.

**Comment by Shinyzenith** [comment]
![image](https://user-images.githubusercontent.com/60808802/141666761-cff77a92-9abe-4b02-9de1-54e80fd876ae.png)

**Comment by UpperCenter** [comment]
My issue is that `xrandr` doesn't detect any of my other monitors. I'm going to reinstall and see if something broke. Maybe some `nvidia` issue.

**Comment by UpperCenter** [comment]
Update:
I fixed this by reinstalling without choosing any `nvidia` drivers, and then it worked. I set my monitors using `arandr` and correctly generated an X11 config. I think this issue was just specific to how I installed the OS the first time.

One last question, where do you get the icons for Polybar? I've been using FontAwesome but they don't look quite the same.

**Comment by angelofallars** [comment]
Glad you were able to solve the issue yourself!

> One last question, where do you get the icons for Polybar? I've been using FontAwesome but they don't look quite the same.

For Axyl, we use [Nerd Fonts](https://www.nerdfonts.com/) for the Polybar icons. You can install them from the AUR. These are the fonts for the [i3 Polybar](https://github.com/axyl-os/axyl-i3wm/blob/master/etc/skel/.config/i3/polybar/config):
```
font-0 = "Source Code Pro Medium:size=10;3"
font-1 = "Iosevka Nerd Font:size=12;3"
font-2 = "Iosevka Nerd Font:size=16;4"
font-3 = "Iosevka Nerd Font:size=18;4"
```

For more tech support, you can expect faster responses by [joining Axyl's Discord server](https://discord.gg/qAXMkQdwjj). 😃
