### ISSUE TITLE
i3wm install

### ISSUE THREAD

**Issue by bluecoat58** [axyl-os/axyl-iso#122]
I don't know if you actually check your spins to see if they work. i3 installs fine, and brings me to the login screen. I enter my credentials, and it leaves me sitting there. I cannot proceed any further. Running on a MS B550 Pro with a Ryzen 5700G.  Every other spin I install works fine.

**Comment by BuiKhanh2007** [comment]
Same

**Comment by benoitlx** [comment]
Same here

**Comment by dainbrump** [comment]
Ditto

**Comment by hydromorphine** [comment]
What the fuck

**Comment by rubixcube199** [comment]
I am cleaning up issues but I want to point out that this spin was kind of dead then. When I release the new iso try again.
