### ISSUE TITLE
Installation window obscured by keybindings info display on VirtualBox

### ISSUE THREAD

**Issue by TarekS93** [axyl-os/axyl-iso#123]
1. **Environment**:
   - VirtualBox Version: (e.g., 7.0)
   - Axyl Linux Version: v22.08

2. **Steps to Reproduce**:
   - Downloaded the Axyl Linux ISO.
   - Created a new virtual machine on VirtualBox.
   - Mounted the Axyl Linux ISO to the virtual machine.
   - Started the virtual machine to initiate the installation process.
   - Upon reaching the installation window, the window is obscured by a program displaying keybindings information.

3. **Expected Behavior**:
   - The installation window should be clearly visible, allowing for smooth installation process.

4. **Actual Behavior**:
   - The installation window is obscured by the keybindings information display, making it impossible to proceed with the installation.

5. **Screenshots**:
![image](https://github.com/axyl-os/axyl-iso/assets/37110556/fc65b22a-be7c-4db1-9885-a37167219051)

**Comment by falkon2** [comment]
any update? happened to me too

**Comment by rubixcube199** [comment]
If you use the keybind to stop conkeww it will work. If that fails make calamaras smaller
