### ISSUE TITLE
dmenu not working

### ISSUE THREAD

**Issue by KingDutchIsBad** [axyl-os/axyl-iso#14]
dmenu doesn't look like it's working when you install xmonad and i3 at the same time. When you open it in the console using the command dmenu-run it gives out this: `warning: no locale support
 XOpenIM failed: could not open input device`

**Comment by Kungger-git** [comment]
This particular error indicates it's related to the system's locale not being set right. What's the output of `locale` if you run it in a terminal?

**Comment by KingDutchIsBad** [comment]
LANG=en_IN
LC_CTYPE="en_IN"
LC_NUMERIC=en_IN
LC_TIME=en_IN
LC_COLLATE="en_IN"
LC_MONETARY=en_IN
LC_MESSAGES="en_IN"
LC_PAPER=en_IN
LC_NAME=en_IN
LC_ADDRESS=en_IN
LC_TELEPHONE=en_IN
LC_MEASUREMENT=en_IN
LC_IDENTIFICATION=en_IN
LC_ALL=

**Comment by Kungger-git** [comment]
how about the output of: `cat /etc/locale.conf`?

**Comment by KingDutchIsBad** [comment]
LANG=en_IN
LC_CTYPE="en_IN"
LC_NUMERIC=en_IN
LC_TIME=en_IN
LC_COLLATE="en_IN"
LC_MONETARY=en_IN
LC_MESSAGES="en_IN"
LC_PAPER=en_IN
LC_NAME=en_IN
LC_ADDRESS=en_IN
LC_TELEPHONE=en_IN
LC_MEASUREMENT=en_IN
LC_IDENTIFICATION=en_IN

**Comment by KingDutchIsBad** [comment]
I'll be trying to reinstall the OS to see if that helps

**Comment by KingDutchIsBad** [comment]
Works after a new install. Something must've gone wrong in the install
