### ISSUE TITLE
Another terminal in iso 

### ISSUE THREAD

**Issue by theCode-Breaker** [axyl-os/axyl-iso#16]
Add a second terminal for a fallback like xfce4-terminal

**Comment by Shinyzenith** [comment]
but why? tty exists

**Comment by theCode-Breaker** [comment]
It's just a suggestion although not required

**Comment by Shinyzenith** [comment]
Alright cool 👍

**Comment by Kungger-git** [comment]
I've added xfce4-terminal in the current release.
