### ISSUE TITLE
calamares off screen

### ISSUE THREAD

**Issue by psaikido** [axyl-os/axyl-iso#22]
At the summary step of the calamares installer the buttons to go 'back' and 'next' were off the bottom of the screen. There was apparently no way to get the process to proceed. I tried every key combination I know to trick it into going 'next' or to get the page to scroll down but after two tries at the whole installation process I gave up.

**Comment by theCode-Breaker** [comment]
Calamares set to floating mode by default to move the window you need to press mod and then drag it or you can use the keybinding to set it to tilling mode.

**Comment by psaikido** [comment]
Aha! Thanks, that's worked - newbie with tiling wms here!

 ---- On Sun, 28 Nov 2021 07:46:50 +0000 Adarsh ***@***.***> wrote ----

**Comment by theCode-Breaker** [comment]
No problem. Enjoy Axyl !!! :)
