### ISSUE TITLE
Request: Please add Key-Bindings of NvChad in documents

### ISSUE THREAD

**Issue by tushargoyalofficial** [axyl-os/axyl-iso#25]
I want to use NvChad like a pro. I am not able to get any Keybinding docs to use NvChad for software developers/Pro user of neovim.
Can you please help me out in this.
BTW, love xmonad of axyl, youtube recommended me a video where one person showcase your OS. No body knows such good distor exists. Approach other youtubers too so as they showcase your distro.

**Comment by Shinyzenith** [comment]
Closing as stale, @Kungger-git please re-open if you're still interested.
