### ISSUE TITLE
Keybindings window

### ISSUE THREAD

**Issue by s0ulHunt3r002** [axyl-os/axyl-iso#27]
How can i delete the keybindings window because i don't need it anymore since i learned them already so i want to delete it.

**Comment by Kungger-git** [comment]
the Eww window is launched from the autostart script of the window manager you're using. See these files and delete anything `eww`:

_**i3wm**_ - `~/.config/i3/bin/autostart.sh`
_**bspwm**_ - `~/.config/bspwm/bspwmrc`
_**dwm**_ - `~/.dwm/autostart.sh`
_**qtile**_ - `~/.config/qtile/scripts/autostart.sh`
_**LeftWM**_ - `~/.config/leftwm/themes/tomorrow-night/up` & `~/.config/leftwm/themes/tomorrow-night/down`
_**SpectrWM**_ - `~/.config/spectrwm/autostart.sh`
_**Xmonad**_ - `~/.xmonad/bin/autostart.sh`

**Comment by prateekmedia** [comment]
@Kungger-git There should be a more visual way to know how to hide it, in the eww popup or in the README.

**Comment by prateekmedia** [comment]
@Kungger-git Also in i3 session this eww window is overlapping other windows which compared to bspwm session doesn't seem to be happening.
