### ISSUE TITLE
Dmenu doesn't work with en_IN locale

### ISSUE THREAD

**Issue by prateekmedia** [axyl-os/axyl-iso#32]
Changing local to en_US fixes this otherwise D-menu straight up refuses to launch.

To reproduce the error:
- Set locale to en_IN using
`sudo localectl set-locale LANG=en_IN`
- Now reboot the system
- Now try to launch dmenu using super key

Temporary fix is to set the locale to
`sudo localectl set-locale LANG=en_IN.UTF-8`

**Comment by Shinyzenith** [comment]
Hi, this is not an axyl bug, closing.
