### ISSUE TITLE
Hide Battery and brightness on desktop computers

### ISSUE THREAD

**Issue by prateekmedia** [axyl-os/axyl-iso#36]
There is red and yellow circles shown in top panel in desktop computers as they don't have brightness or battery, It would look good if they are hidden.

**Comment by theCode-Breaker** [comment]
Okay but you can remove it yourself. Axyl gives you pre-configured wm so that you don't have to get into hassle of configuring them but if you want to apply changes then read the documentations and wiki. 
Also mention which wm you are using

**Comment by prateekmedia** [comment]
I am using default i3, yes I have configured that but I thought if it is applied by default then it would be good.

**Comment by theCode-Breaker** [comment]
Okay cool we will look into it
