### ISSUE TITLE
Multi-language  keyboard layouts support

### ISSUE THREAD

**Issue by endlesskwazar** [axyl-os/axyl-iso#38]
VM: i3

After install, I've used xfce4-keyboard-settings to add layouts and set shortcut to change layouts. But it will give nothing.
Only manual editing of 00-keyboard.conf in x11 settings worked for me.

And after adding layouts, there are no changes on the top panel. And it's hard to know which layout used now, and what will be using after switching.

What is Axyl distro point of view on multi-language's layout users? How they need to solve this task? And will distro help with this?

**Comment by tuxos78** [comment]
Hi.
add your layout to the "ru" location. switching ctrl+shift
.config/i3/config

#switching keyboard layouts
exec --no-startup-id setxkbmap -model pc105 -layout us,ru -option grp:ctrl_shift_toggle

https://github.com/polybar/polybar/wiki/Module:-xkeyboard
