### ISSUE TITLE
[Request] Switch to Rofi

### ISSUE THREAD

**Issue by prateekmedia** [axyl-os/axyl-iso#39]
Rofi is a successor of Dmenu, That's it (#32)

**Comment by theCode-Breaker** [comment]
Ye rofi is cool but let's see what Matt has to say as for the installation set your locale to en_US for now or if you want to change locale after installation then do `localectl set-locale LANG=en_US.UTF-8`

**Comment by 4ldas** [comment]
agree

**Comment by Shinyzenith** [comment]
Although https://github.com/axyl-os/axyl-iso/issues/32 is not our bug, we will consider rofi.
