### ISSUE TITLE
[Suggestion] Add i3-gap

### ISSUE THREAD

**Issue by DashCruft** [axyl-os/axyl-iso#4]
Hello,

I was wondering if it would be possible to add i3 or i3-gaps to this axyl project? It would be awesome!

Thanks

**Comment by LogicApples** [comment]
> Hello,
> 
> I was wondering if it would be possible to add i3 or i3-gaps to this axyl project? It would be awesome!
> 
> Thanks
> 
> 

NANI?

**Comment by Kungger-git** [comment]
i3wm is now included in Axyl.. It's even the Default Window Manager for the Live Environment. Check out the new Release. :>
