### ISSUE TITLE
[Request] zip/rar/7z file support out of the box

### ISSUE THREAD

**Issue by endlesskwazar** [axyl-os/axyl-iso#40]
There is no support of archives files when using thunar out of the box.

**Comment by 4ldas** [comment]
most linux distros dont come with mentioned archive file things out of the box, just install manually, theres no need to have it out of the box and can be considered bloatware in a way

**Comment by Shinyzenith** [comment]
Although support has been merged, this would be out of scope for a minimal distribution imo.
