### ISSUE TITLE
HTOP and polybar widget shows different memory usage value

### ISSUE THREAD

**Issue by endlesskwazar** [axyl-os/axyl-iso#41]
VM: bspwm

At the beginning I was thought it because widget need time to sync actual value, but event with 3-5 min it will not show actual ram usage value.

From system start, polybar shows that fresh system boot using ~700 MB ram, but htop shows ~400 MB ram.

![Screenshot_2022-01-01-11-40-26_1920x1080](https://user-images.githubusercontent.com/20013642/147848025-eb5f6307-0d1c-4a2b-b815-0421d1d43ef9.png)

**Comment by angelofallars** [comment]
Hi! Each program has a different way of measuring RAM usage. For example, one program might measure RAM by GBs (gigabytes, multiples of 1000) and another with GiBs (gibibytes, multiples of 1024). There is not really a standardized way of measuring RAM. You can open an issue in the repositories of [polybar](https://github.com/polybar/polybar) and [htop](https://github.com/htop-dev/htop) about their memory usage values if you want.
