### ISSUE TITLE
[Request] Switch polybar RAM usage from MiB to GB

### ISSUE THREAD

**Issue by endlesskwazar** [axyl-os/axyl-iso#42]
I think, it will be more compact and meaningful if ram usage widget will show RAM usage in GB.

For example:
1652 MiB -> 1.65 GB

**Comment by mariejie** [comment]
You can edit it in `polybar/module`, find memory section, edit `mb_used` to `gb_used`

**Comment by Shinyzenith** [comment]
Closing as stale, feel free to configure polybar to your taste as per the provided suggestion.
