### ISSUE TITLE
[Request] Replace display manager

### ISSUE THREAD

**Issue by ghost** [axyl-os/axyl-iso#45]
AxylOS is currently a very polished and productive experience, it's a daily driver. 
It currently uses LXDM. While almost everything works fine with LXDM, it isn't compatible with [optimus-manager](https://github.com/Askannz/optimus-manager), which is a utility to switch between integrated and discrete graphics on nvidia laptops, allowing to switch off the nvidia GPU completely.
AxylOS without optimus-manager uses prime render offload, which keeps the nvidia discrete graphics running at minimum power. While this is better than running on nvidia graphics at full power, since the discrete GPU is still on it draws some power. Using optimus-manager it would draw zero power.
Optimus-manager requires to use LightDM, SDDM or GDM as display manager to work.
I kindly propose AxylOS to abandon LXDM in favor of LightDM or SDDM so optimus-managar can be used, that way nvidia laptop users can get more battery life out of their laptops when using AxylOS.

**Comment by 4ldas** [comment]
i think i need to use optimus-manager it also for my external monitor to work aswell so agree i guess

**Comment by 4ldas** [comment]
id love to see wayland display manager being used also even tho i think they have quite bad support for nvidia so far not sure tho, with fedora it worked fine on my rtx 3060 laptop but the external monitor wasnt being detected or couldnt use i think i didnt debug much

**Comment by Shinyzenith** [comment]
This is relatively easy to implement, lets see what @Kungger-git thinks.
