### ISSUE TITLE
[BUG] ewwconky is ontop all windows in some window managers

### ISSUE THREAD

**Issue by tifasoftware** [axyl-os/axyl-iso#46]
In i3 and DWM, the conky is ontop all of the windows regardless of configuration.

**Comment by flamedmg** [comment]
same on qtile, but dmw is fine for me.

**Comment by Abhysek** [comment]
Did anyone find the solution?

**Comment by tifasoftware** [comment]
In arco linux, in almost every WM, the regular conky is used and doesnt have the issue with ewwconky.

**Comment by angelofallars** [comment]
@tifasoftware @flamedmg @Abhysek 

### Removing Eww
To remove eww, edit these following scripts depending on the Window Manager you are currently using:
- _**DWM:**_ `~/.dwm/autostart.sh`
- _**Xmonad:**_ `~/.xmonad/bin/autostart.sh`
- _**BSPWM:**_ `~/.config/bspwm/bspwmrc`
- _**i3wm:**_ `~/.config/i3/bin/autostart.sh`
- _**Spectrwm:**_ `~/.config/spectrwm/autostart.sh`
- _**Qtile:**_ `~/.config/qtile/scripts/autostart.sh`
- _**Leftwm:**_ `~/.config/leftwm/themes/current/up`

And delete/comment out the lines:
```
# Launch Conkeww
#sed -i "s/colors\/color-.*/colors\/color-one-dark.yuck\")/g" $HOME/.config/conkeww/eww.yuck
#eww --config $HOME/.config/conkeww/ open conkeww-main
```
