### ISSUE TITLE
[Request] Add a few applications

### ISSUE THREAD

**Issue by tifasoftware** [axyl-os/axyl-iso#47]
I have tested out your distro, and I believe it could use some of these below.
1. Nitrogen, it is a minimalist application that sets the background.
2. Try to pre-include vmtools like Arco Linux did.
3. Add chaotic repo.

**Comment by mariejie** [comment]
1. Yes, feh is suck, stupid way to change wallpaper, i don't want to copy and paste it in config folder everytime, endeavourOS pre-install nitrogen, it very easy to change wallpaper.
2. Nah 
3. Nah
4. Just pre-install pure nvim and vim, the config Axyl used is suck

**Comment by Shinyzenith** [comment]
Out of scope for the project - matt would prefer to keep it minimal. 
@Kungger-git if you feel otherwise, re-open this issue.
