### ISSUE TITLE
[Bug] On ethernet, wifi shows with %essid%

### ISSUE THREAD

**Issue by tifasoftware** [axyl-os/axyl-iso#48]
When on ethernet, the wifi widget shows saying %essid%.

**Comment by ismataka** [comment]
I got the same trouble.

**Comment by lknows** [comment]
This is by no means a true fix(That would require changing the network module in a way that is beyond me and the time I have to research things) but for those that are annoyed and want a quick solution to remove this specific widget:

Find your polybar config directory. I use i3, so mine was located at `~/.config/i3/polybar/`.
If you open the `config` file here, you should see around line 52ish a `modules-left = `...

Here you need to remove the word `network` from this line of code and restart your wm and your %essid% should be gone. You can also remove the `MLD` and `MRD` as well if you want.

I hope to fix this bug for real later when I have time. It's on the list, but the list is large

**Comment by lknows** [comment]
Still not a true fix, but zeroing in on the issue, i found where that `%essid%` is referenced. `~/.config/i3/polybar/modules` is the file location for me on i3.

Around line 320, `label-connected = ...` needs changing. I would replace %essid% with any of the tokens mentioned in [polybar's wiki](https://github.com/polybar/polybar/wiki/Module:-network) - > Module:-network:

```
; All labels support the following tokens:
;   %ifname%    [wireless+wired]
;   %local_ip%  [wireless+wired]
;   %local_ip6% [wireless+wired]
;   %essid%     [wireless]
;   %signal%    [wireless]
;   %upspeed%   [wireless+wired]
;   %downspeed% [wireless+wired]
;   %netspeed%  [wireless+wired] (%upspeed% + %downspeed%) (New in version 3.6.0)
;   %linkspeed% [wired]
;   %mac%       [wireless+wired] (New in version 3.6.0)
```


Here's a screencap of file if it helps:
![Screenshot_2022-08-13_15:11:45](https://user-images.githubusercontent.com/7243001/184509461-b0cf7d9a-c28b-4635-9a01-d851febb8155.png)
