### ISSUE TITLE
checksums

### ISSUE THREAD

**Issue by 4ldas** [axyl-os/axyl-iso#49]
add checksums to releases to prevent supply chain attacks incase i guess

**Comment by JustANormalTinker** [comment]
+1 but not for supply chain attacks instead for verifying if my download has errors or not

**Comment by Peppe61** [comment]
Looking forward to trying the new iso out, but the sha256sum.txt file and a sha256sum.txt.gpg file are not available? Or a md5sums.txt? At least cannot find them on the download page. Please advise, bcs I'd like to verify the iso before trying it out.

**Comment by lknows** [comment]
> Looking forward to trying the new iso out, but the sha256sum.txt file and a sha256sum.txt.gpg file are not available? Or a md5sums.txt? At least cannot find them on the download page. Please advise, bcs I'd like to verify the iso before trying it out.

I'm relearning file integrity tools again, so bare with me, but I added a sha256 file to the newest release for verification:
https://github.com/axyl-os/axyl-iso/releases/download/v22.10/axyl-2022.08.10-x86_64.iso.sha256

 To my knowledge the other algorithms mentioned are too outdated to bother with. Lemme know if I goofed please or what else I can do to get this one closed. I'm moving on to other features, but will always revisit critical issues like these when necessary.

**Comment by Peppe61** [comment]
The power of open source! Just downloaded and checked it; the values match. Afaiac the issue can be closed, tonight I'll be installing i3. Might be I'll open another issue, in a first run last Saturday all wm's, except spectrwm, worked great. With spectr I was greeted with a black screen. But back on subject: thanks a lot!
