### ISSUE TITLE
Installation failed but live usb working in grub... unplugged

### ISSUE THREAD

**Issue by autonaut-x** [axyl-os/axyl-iso#52]
i am in the liveuser now, in firefox, everything seems operational. i've installed VS Code. 
my T420 has had just about every distro thrown at it but Axyl has failed to install (or at least shows the error, but i'm currently in the environment) and now there's this strange behaviour.

**Comment by Shinyzenith** [comment]
What's the error? What's the strange behavior that you're talking about?

**Comment by Shinyzenith** [comment]
No reply from author, closing as stale.
