### ISSUE TITLE
Unable to install or open installation prompt, open firefox, file manager (thunar) 

### ISSUE THREAD

**Issue by willosdalb** [axyl-os/axyl-iso#55]
Not sure if its just me but i tried opening apps like firefox, file manager and trying to intall on my system it just doesnt work on LIVE CD

**Comment by thyeun** [comment]
Are you using radeon display card? if yes
Try just to include this line before it boot into live CD `radeon.modeset=0` (press advanced and press tab to include it)

**Comment by Shinyzenith** [comment]
No reply from author on suggested fix. Closing as stale, please re-open if it's still relevant.
