### ISSUE TITLE
[Request] Append axy-repo

### ISSUE THREAD

**Issue by karak1974** [axyl-os/axyl-iso#58]
Under version **2021.12.2**, I tried to switch to lightDM from the default LxDM. I had some issue with lightDM and went back to LxDM. After that I recognized that the `axyl-lxdm-theme` package isn't in `axyl-repo` repository. May I suggest the development to extend the repository with this additional package?

**Comment by Shinyzenith** [comment]
Closing as stale. `axyl-lxdm-theme` is in `axyl-repo` now.

**Comment by Shinyzenith** [comment]
https://github.com/axyl-os/axyl-repo/tree/master/x86_64
