### ISSUE TITLE
No window opacity in alacritty

### ISSUE THREAD

**Issue by SturlaIdsoe** [axyl-os/axyl-iso#59]
Alacritty have no opacity in qtile.

This is due to alacritty.yml have window.opacity: 0.8 instead of 
window: 
  opacity: 0.8 

which will make alacritty have an opacity.

**Comment by mariejie** [comment]
`window.opacity: 0.8` is correct, nothing wrong with it, you need to edit `picom.config`  too to have opacity

**Comment by Shinyzenith** [comment]
Closing as stale, please re-open if it's still relevant.
