### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by flazz01** [axyl-os/axyl-iso#6]
Any mirror for download? because i can't download ISO from here. I don't know why, it just takes forever for download to start.

**Comment by LogicApples** [comment]
you can maybe use other browser to download. I don't think there are any mirrors

**Comment by flazz01** [comment]
> you can maybe use other browser to download. I don't think there are any mirrors

Use firefox and chrome and i get the same result.

**Comment by LogicApples** [comment]
have you tried a different device?

**Comment by flazz01** [comment]
> have you tried a different device?
Success download from my phone 😊

**Comment by LogicApples** [comment]
> > have you tried a different device
> 
> Download success from my phone 😊

That's great :). I know you will love this OS.
