### ISSUE TITLE
Package manager issues

### ISSUE THREAD

**Issue by OrrellElectrics** [axyl-os/axyl-iso#60]
Point blank refuses to install for me giving a package manager issue

Works fine in liveuser gets about 60% through installer then gives failed to install message

Have even tried November release

![IMG_20220226_162309](https://user-images.githubusercontent.com/76068083/155852016-1b53c853-5caa-4002-87ee-f5537b1b9db5.jpg)

**Comment by OrrellElectrics** [comment]
Is this the issue? The repo path is wrong? It goes to a 404

Inside liveuser pacman.conf:

![IMG_20220226_173456](https://user-images.githubusercontent.com/76068083/155853293-73759638-a9b4-4e23-a568-02a15c21ee47.jpg)
![IMG_20220226_173548](https://user-images.githubusercontent.com/76068083/155853298-42ddb999-78bd-44fe-aed6-5c98a2025534.jpg)
![IMG_20220226_173552](https://user-images.githubusercontent.com/76068083/155853300-5d89ea5e-7516-4b43-acea-b06544e9697b.jpg)

**Comment by angelofallars** [comment]
@OrrellElectrics

We just released a [new version](https://github.com/axyl-os/axyl-iso/releases/tag/v22.04) of Axyl (v22.04), can you download it and check it out if it works?

**Comment by dliraf** [comment]
I got the same issue when trying to install v22.04 and v21.12 in a vm
Ran Calamares in debug mode and saw multiple dns resolve issues when it tried to run Pacman.
Tried 3-4 times but always with the same result.

Opened a shell and tried to ping the same hosts and it worked without any issues.
Checked /etc/resolv.conf and saw it didn't contain any nameservers.
Added a nameserver in /etc/resolv.conf to attempt a workaround and have now tried twice and both were successful installations.

**Comment by sgt7io** [comment]
I attempted an install of v2022.04.01. The installer failed with the following message:
Package Manager error
Details:
The package manager could not prepare updates. The command <pre>pacman</pre> returned error code 1.

**Comment by lubbbert** [comment]
I had the same error while trying to install Axyl on VMWare virtual machine.
I've tried to install almost every WM and got the same error.

**Comment by Shinyzenith** [comment]
> Is this the issue? The repo path is wrong? It goes to a 404
> 
> Inside liveuser pacman.conf:
> 
> ![IMG_20220226_173456](https://user-images.githubusercontent.com/76068083/155853293-73759638-a9b4-4e23-a568-02a15c21ee47.jpg) ![IMG_20220226_173548](https://user-images.githubusercontent.com/76068083/155853298-42ddb999-78bd-44fe-aed6-5c98a2025534.jpg) ![IMG_20220226_173552](https://user-images.githubusercontent.com/76068083/155853300-5d89ea5e-7516-4b43-acea-b06544e9697b.jpg)

Hi, that's now how you access these links 😁. $repo gets replaced with the repository name and $arch with x86_64 in your case. I will look into this issue when I get time.

**Comment by lknows** [comment]
@OrrellElectrics 
I'd really try the script that creates an updated iso for you and use that instead. It solved a lot of issues for me.
You can find it in the installation-scripts/ directory. See link here: https://github.com/axyl-os/axyl-iso/tree/master/installation-scripts

See this closing comment for more info: #84 (comment)

@lubbbert Many users run into issues trying axyl on a VM, I would really try a liveusb instead
