### ISSUE TITLE
pacman error due to untrusted keyring

### ISSUE THREAD

**Issue by marcoslaredo** [axyl-os/axyl-iso#61]
I ran the live environment very well and then went to install it on my test machine (no virtual).
I was connected by RJ-45 and the progress was going without errors (at the installer) and finished without any error or warning.
When I restarted the machine, no package was updated and the whole system was out of the style - my i3 opened with an error bar at the bottom of the screen.
I opened the terminal and tried to update the whole system using `sudo pacman -Syyu` - and every time I got some errors about untrusted keys.
I searched for the error and found out that the **archlinux-keyring package was not up-to-date**.
The only way I found to fix it was running the live section again and before launch the installer, open a terminal and update the archlinux-keyring by `sudo pacman -Sy archlinux-keyring`, then I run the installer and all the desktops were installed fine.
After the installation process, I ran again the command to update the keyring before update all the system with the `sudo pacman -Syyu`.
And from my new Axyl installation I'm reporting this issue :)

**Comment by Abhysek** [comment]
https://bbs.archlinux.org/viewtopic.php?id=226770 Last comment has the solution.

**Comment by marcoslaredo** [comment]
Thank you @Abhysek.
I actually found the workaround for this issue.
I ran the `sudo pacman -Sy archlinux-keyring` that solves the problem.
I just shared the experience so you guys can fix the distro.
