### ISSUE TITLE
How to remove this "code" output from terminal

### ISSUE THREAD

**Issue by apipit** [axyl-os/axyl-iso#62]
https://ibb.co/QpGTfHZ thanks

**Comment by thyeun** [comment]
@apipit open up your `config,fish`, and uncomment the line below

Before
```
alias pipes='pipes -p 5 -R -t 1 -r 0'
 colorscript -r
```
After
```
alias pipes='pipes -p 5 -R -t 1 -r 0'
#colorscript -r
```
After you uncomment the `colorscript -r`, you wont see any extra script appear on your `Alacritty` terminal.

**Comment by apipit** [comment]
thanks for the response, but actually i've already figured that out,
