### ISSUE TITLE
PGP keys wont import

### ISSUE THREAD

**Issue by Kvrdja** [axyl-os/axyl-iso#63]
When trying to install something with pacman, at the end it asks to import PGP keys but then it says they`re corrupted or invalid and i cannot install anything.

**Comment by LPRegen** [comment]
Hi! I had the same problem and the solution was to run `pacman -S archlinux-keyring`. 
If don't work for you, you can google "error importing pgp keys arch linux" or something like the error you have and you will find a lot of posts from the Arch forum.

**Comment by angelofallars** [comment]
@Kvrdja did installing `archlinux-keyring` work for you?

**Comment by c0dename47** [comment]
work for me! thanks

**Comment by fostopern** [comment]
> Hi! I had the same problem and the solution was to run `pacman -S archlinux-keyring`. 
> If it doesn't work for you, you can google "error importing pgp keys arch linux" or something like the error you have and you will find a lot of posts from the Arch forum.

Works for me!!!!

**Comment by Shinyzenith** [comment]
Rule of thumb, always reinstall `archlinux-keyring` if you get tons of PGP errors. Not an axyl bug.
