### ISSUE TITLE
Xmonad and dwm is broken

### ISSUE THREAD

**Issue by mariejie** [axyl-os/axyl-iso#65]
I'm install Xmonad and dwm, after finish, I'm reboot and change from i3 to Xmonad/dwm, i can't access into it, it keep asking password, but i3 work find until update `base-devel` from #64

**Comment by thyeun** [comment]
for Xmonad, you need to run `xmonad --recompile` if you been upgrade xmonad to newer version from `paru -Syu`, you can run the recompile command from i3, than login back to xmonad. after that you wont see the message keep ask you about the password.

**Comment by mariejie** [comment]
@thyeun thanks dude 🥰
