### ISSUE TITLE
Unable to install the axyl-os through calamers

### ISSUE THREAD

**Issue by pakosaan** [axyl-os/axyl-iso#66]
the keybindings widgtets hide the calamer windows and the qemu virtual manager wont scale the display so cannot install it .Any way to fix?

**Comment by mariejie** [comment]
comment 3 lines in `.config/i3/bin/autostart.sh` 
```
# Launch Conkeww
# sed -i "s/colors\/color-.*/colors\/color-one-dark.yuck\")/g" $HOME/.config/conkeww/eww.yuck
# eww --config $HOME/.config/conkeww/ open conkeww-main
```
hope this can help :+1:

**Comment by angelofallars** [comment]
@pakosaan any updates on this?

**Comment by vinksz** [comment]
Same thing (when choosing spectrwm) with 22.04 iso. 

The package manager could not prepare updates.
The command <pre>pacman</pre> returned with error code 1.

**Comment by lubbbert** [comment]
> the keybindings widgtets hide the calamer windows and the qemu virtual manager wont scale the display so cannot install it .Any way to fix?

You can turn off keybindings widgtets by pressing [S] + Shift + E

**Comment by tim9135** [comment]
> > the keybindings widgtets hide the calamer windows and the qemu virtual manager wont scale the display so cannot install it .Any way to fix?
> 
> You can turn off keybindings widget Conkeww by pressing [S] + Shift + E

Yeah, I can get rid of the window and continue the install process, but right now I have faced another problem in Summary session. I can't see the button on the bottom in the Summary. How can I continue the install process? I am using VMware Workstation 16 install axyl.
![axyl](https://user-images.githubusercontent.com/47561045/164759814-c6fa0e6d-8e3c-4088-85a3-6a270459e936.png)

**Comment by lubbbert** [comment]
> > > the keybindings widgtets hide the calamer windows and the qemu virtual manager wont scale the display so cannot install it .Any way to fix?
> > 
> > 
> > You can turn off keybindings widget Conkeww by pressing [S] + Shift + E
> 
> Yeah, I can get rid of the window and continue the install process, but right now I have faced another problem in Summary session. I can't see the button on the bottom in the Summary. How can I continue the install process? I am using VMware Workstation 16 install axyl. ![axyl](https://user-images.githubusercontent.com/47561045/164759814-c6fa0e6d-8e3c-4088-85a3-6a270459e936.png)

If I'm not mistaken, in live mode you can move tiles using [S] + Shift + [Arrow left/right/up/down].

**Comment by kitepad** [comment]
I suggest set default resolution to 1024x768, 800x600 is not good for installer.

**Comment by Shinyzenith** [comment]
Closing issue as stale. Please open a new issue for feedback regarding conky hiding calamares if this issue is still valid.
