### ISSUE TITLE
error: failed to synchronize all databases (unexpected error)

### ISSUE THREAD

**Issue by tuxos78** [axyl-os/axyl-iso#67]
Hi

sudo pacman -Syu
:: Updating package databases...
 axyl-repo is up to date
 axyl-repo-3party.db failed to download
 core is up to date
 extra is up to date
 community is up to date
error: failed to get the file 'axyl-repo-3party.db' из axyl-os.github.io : The requested URL returned error: 404
error: failed to synchronize all databases (unexpected error)

**Comment by thyeun** [comment]
@tuxos78 You have to make change `/etc/pacman.conf` as below and re-run `paru -Syu` or `sudo pacman -Syu`

Before
```
[axyl-repo-3party]
SigLevel = Optional TrustedOnly
Server = https://axyl-os.github.io/$repo/$arch
```
After
```
[axyl-3party-repo]
SigLevel = Optional TrustedOnly
Server = https://axyl-os.github.io/$repo/$arch
```
Due to that creator had made changed/updated yesterday.

**Comment by tuxos78** [comment]
Thank you very much,  the update is working
