### ISSUE TITLE
Error with a fresh install  --returned error code 1

### ISSUE THREAD

**Issue by tnkmon** [axyl-os/axyl-iso#68]
After trying to install any of the environments I get the error:

"The package manager could not prepare updates. The command `<pre> pacman </pre>`  returned error code 1. 

After this, when trying to install again in the calamar installer it does not detect the options for automatic hard disk partitioning. Please Help 👍

**Comment by suryanisaac** [comment]
Can confirm. Just tried this.

**Comment by tnkmon** [comment]
still no information, I did tests in vmachine, without positive result, once the problem is solved I plan to install it in hardware

**Comment by angelofallars** [comment]
@tnkmon @farridav @suryanisaac 

We just released a [new version](https://github.com/axyl-os/axyl-iso/releases/tag/v22.04) of Axyl (v22.04), can you download it and check it out if it works?

**Comment by DashCruft** [comment]
Doesn't matter. The error is still present...

**Comment by angelofallars** [comment]
> Doesn't matter. The error is still present...

By any chance, are you running it in a virtual machine? Specifically, QEMU? Some users have reported that the Calamares installer does not work on QEMU, but works in other virtualization software like VirtualBox.

**Comment by DashCruft** [comment]
> By any chance, are you running it in a virtual machine? Specifically, QEMU? Some users have reported that the Calamares installer does not work on QEMU, but works in other virtualization software like VirtualBox.

Nope. I think there's something up with the Pacman mirrors. I tried the recent version and put it on a usb stick. Boot into it and then once the installation went ahead, it gave out the error

**Comment by angelofallars** [comment]
> Nope. I think there's something up with the Pacman mirrors. I tried the recent version and put it on a usb stick. Boot into it and then once the installation went ahead, it gave out the error

Can you run `sudo pacman -Syu` in a terminal in the live install and see if it works?

**Comment by suryanisaac** [comment]
I will try and let you know

**Comment by DashCruft** [comment]
I think your pacman servers seem to be completely down.

https://axyl-os.github.io/$repo/$arch
https://axyl-os.github.io/$repo/$arch

**Comment by tnkmon** [comment]
At the time the ISO was released I was able to install the OS without inconvenience, I have not tried it today I will close this case, because the fault I had was solved

however I think I will open a case for problems after installation specifically with qtile :(
