### ISSUE TITLE
failed to install "<pre> pacman <pre>"

### ISSUE THREAD

**Issue by juanda3132** [axyl-os/axyl-iso#69]
The error that occurs is: "failed retrieving file 'axyl-repo-3party.db' from axyl-os.github.io " the requested URL returned error 484

and "failed to synchronize all databases"

**Comment by Infinitybeond1** [comment]
im having this same issue, can someone pls help

**Comment by tuxos78** [comment]
Вы должны внести изменения /etc/pacman.conf, как показано ниже, и повторно запустить paru -Syuилиsudo pacman -Syu

До

[axyl-repo-3party]
SigLevel = Optional TrustedOnly
Server = https://axyl-os.github.io/$repo/$arch
После

[axyl-3party-repo]
SigLevel = Optional TrustedOnly
Server = https://axyl-os.github.io/$repo/$arch


https://github.com/axyl-os/axyl-iso/issues/67

**Comment by Infinitybeond1** [comment]
Yes I did that, I think it's an issue with calamares running the pacman command with no flags, which would ussualy return 1

**Comment by DaxGoon** [comment]
I am having this issue too.

**Comment by angelofallars** [comment]
@juanda3132 @DaxGoon @Infinitybeond1

We just released a [new version](https://github.com/axyl-os/axyl-iso/releases/tag/v22.04) of Axyl (v22.04), can you download it and check it out if it still errors?

**Comment by juanda3132** [comment]
> @juanda3132 @DaxGoon @Infinitybeond1
> 
> Acabamos de lanzar una [nueva versión](https://github.com/axyl-os/axyl-iso/releases/tag/v22.04) de Axyl (v22.04), ¿puedes descargarla y verificar si todavía tiene errores?

When installing in a virtual machine, the installer works correctly, it seems that the error has been solved, I'm going to try it on a physical machine, thanks, and a version with runit would be great.

**Comment by angelofallars** [comment]
> > @juanda3132 @DaxGoon @Infinitybeond1
> > Acabamos de lanzar una [nueva versión](https://github.com/axyl-os/axyl-iso/releases/tag/v22.04) de Axyl (v22.04), ¿puedes descargarla y verificar si todavía tiene errores?
> 
> When installing in a virtual machine, the installer works correctly, it seems that the error has been solved, I'm going to try it on a physical machine, thanks, and a version with runit would be great.

You're welcome! We're already starting development on an ISO with Artix Linux and runit. Expect a runit release later this month.

**Comment by DaxGoon** [comment]
> @juanda3132 @DaxGoon @Infinitybeond1
> 
> We just released a [new version](https://github.com/axyl-os/axyl-iso/releases/tag/v22.04) of Axyl (v22.04), can you download it and check it out if it still errors?

Thanks. Trying at the moment, I will let you know if I encounter some issues.
Much appreciated this effort you are putting on this! Cheers!!
