### ISSUE TITLE
Repository is asking for password while trying to download the iso

### ISSUE THREAD

**Issue by rivubardhan1996** [axyl-os/axyl-iso#70]
I can't download the iso when I try it says it needs a username and a password

**Comment by angelofallars** [comment]
Can you elaborate? Are you downloading from the [GitHub releases](https://github.com/axyl-os/axyl-iso/releases) section?

**Comment by rivubardhan1996** [comment]
Yes thats correct.

**Comment by Shinyzenith** [comment]
> Can you elaborate? Are you downloading from the [GitHub releases](https://github.com/axyl-os/axyl-iso/releases) section?

I think the repo link mentioned in pacman conf is incorrect, that leads to the password error.

**Comment by lknows** [comment]
@rivubardhan1996 
I'd really try the script that creates an updated iso for you and use that instead. It solved a lot of issues for me.
You can find it in the installation-scripts/ directory. See link here: https://github.com/axyl-os/axyl-iso/tree/master/installation-scripts

See this closing comment for more info: #84 (comment)
