### ISSUE TITLE
No funciona el instalador

### ISSUE THREAD

**Issue by abdiasriver** [axyl-os/axyl-iso#71]
He tratado de instalar la distribucion ,mas no he obtenido un resultado afirmativo
- ya realize el cambio de repositorio 3party y no funciona.

Sugerencia: podrian actualizar la iso?
o alternativamente algun manual de crear la propia iso desde el repo github

**Comment by angelofallars** [comment]
Hola @abdiasriver! (Perdon si mi español es malo)

Puedes instalar [la ISO nueva](https://github.com/axyl-os/axyl-iso/releases/tag/v22.04) (version 22.04) que acabamos de hacer? A ver si funciona. Gracias!

**Comment by brew-o-doro** [comment]
the new version of the installer is not working for me either. I keep getting error 1 message

**Comment by lknows** [comment]
@abdiasriver 
¿De dónde sacaste tu iso? Si la descargaste de un mirror, yo probaría el script que crea una iso actualizada para ti y usaría eso en su lugar. A mí me solucionó muchos problemas.
Puedes encontrarlo en el directorio installation-scripts/. Vea el enlace aquí: https://github.com/axyl-os/axyl-iso/tree/master/installation-scripts

Ver este comentario final para más información: #84 (comentario)

@brew-o-doro 
Where did you get your iso? if you downloaded it from a mirror, I'd really try the script that creates an updated iso for you and use that instead. It solved a lot of issues for me.
You can find it in the installation-scripts/ directory. See link here: https://github.com/axyl-os/axyl-iso/tree/master/installation-scripts

See this closing comment for more info: #84 (comment)
