### ISSUE TITLE
The image may not be UEFI

### ISSUE THREAD

**Issue by Mehybinator** [axyl-os/axyl-iso#74]
When i try to boot into the new iso in efi mode , i get two lines basically saying no UEFI , is it just not supported or is it something else ?

**Comment by kabeier** [comment]
I had a similar issue but I redownload the iso and use unetbootin to remake the USB and it worked.  Yet it did not label the volume correctly and when I try to boot axyl from the menu It is trying to mount by label and then the shell shows no by_label directory

**Comment by JustANormalTinker** [comment]
I found the issue, the EFI partition in the ISO is FAT16

**Comment by lknows** [comment]
@Mehybinator Did you get your iso from a mirror? If so, I would really try the build script from the `installation-scripts` directory, because it will create an updated iso for you. It solved many issues for me.

Let us know if @kabeier's solution worked please
