### ISSUE TITLE
The ISO is created with FAT 16 EFI partition

### ISSUE THREAD

**Issue by JustANormalTinker** [axyl-os/axyl-iso#75]
Due to this most consumer level will refuse to boot off of it. The fix is to make it FAT 32.

**Comment by lknows** [comment]
Could you try expounding upon your issue? How did you create your iso? Did you use the build script in the `installation-scripts` directory?

**Comment by JustANormalTinker** [comment]
I didn't not create a ISO, just downloaded it from the release page

**Comment by lknows** [comment]
I'd really try the build.sh script that creates an updated iso for you and use that instead. It solved a lot of issues for me.
You can find the build script in the installation-scripts/ directory. See link here: https://github.com/axyl-os/axyl-iso/tree/master/installation-scripts

See this closing comment for more info: https://github.com/axyl-os/axyl-iso/issues/84#issuecomment-1179817510
