### ISSUE TITLE
Login loop

### ISSUE THREAD

**Issue by VVack** [axyl-os/axyl-iso#76]
Recently tried installing both the dwm and spectrwm versions to my Lenovo yoga 730-15. Live image seems to be working correctly and I am successfully able to install. However, when I try to login the computer will go to a blue screen for a few seconds then boot me back to the login screen. I have verified the password is correct, but I am unable to make it past the login screen. This has occurred on both installations, I may try xmonad next to see what occurs.

**Comment by parz3val** [comment]
Did you enable automatic login anyway? I had the same issue when I installed with automatic login enabled but worked when I disabled it. Try i3wm first and change to dwm after you boot if that works for you.

**Comment by coral-hungus** [comment]
Installing with i3wm first does work. Thanks for the workaround.

**Comment by lknows** [comment]
@VVack Do you have any update? Many users have had issues with virtual machines, and I'd advocate trying a liveusb instead.

Do let us know if @coral-hungus solution worked so we can close this issue thread as solved.

**Comment by iptoux** [comment]
Hey,

i tested this error now for 2 days,

i'm using an Proxmox machine, all desktops work, only dwm won't work.

- It don't work with/without autologin
- It doesn't matters wich graphics card are selected (in proxmox)
- It doesn't matters wich Bios variant (seabios/efi) is selected
- It doesn't matters wich machine type is selected

what i noticed, the installation process of dwm ends to fast (compared to all other Wm), mayybe there is an error durring the installation what skips the install of the wm, because after reboot, the wm is not selectable, there is no one installed.

**Comment by Giuszm** [comment]
Same issue, tried qtile, even if i set it to automatic login the password prompt still shows and i'm unable to login due to the problem you explained

**Comment by Kenshin7** [comment]
I don't know if this will work for anyone, but I also ran into this problem while trying to install XMonad as my WM. Here's what I did to make it work for me, hopefully it works for you too:

- After installing Axyl with the WM you want selected, reboot and enter recovery mode.
- Login and run the following:
    - `NetworkManager` (this will connect you to wifi or whatever)
    - `pacman -S archlinux-keyring` (for updating packages soon)
    - `pacman -Syu` (update stuff)
    - `pacman -S axyl-xmonad` (got it from here: https://github.com/axyl-os/axyl-iso/wiki/%28FAQ%29How-to-Config:--Themeing%2C-Custom-Adjustment-Modification-Data%2C-Details%2C-and-Other-General-Information-in-FAQ-Format)
    - `cp -r /etc/skel/.xmonad/ /home/your_user/.xmonad/` (make sure to replace `your_user` with the user you're going to sign in as
    - `exit` (this should take you back to the login screen and hopefully display XMonad in the bottom-left menu. if not, try rebooting)
- Select XMonad in the bottom-left menu and log in.

I'm barely getting into like Linux stuff so I can't properly explain a lot of it, but glhf.

**Comment by Minepool9** [comment]
> I don't know if this will work for anyone, but I also ran into this problem while trying to install XMonad as my WM. Here's what I did to make it work for me, hopefully it works for you too:
> 
> * After installing Axyl with the WM you want selected, reboot and enter recovery mode.
> * Login and run the following:
>   
>   * `NetworkManager` (this will connect you to wifi or whatever)
>   * `pacman -S archlinux-keyring` (for updating packages soon)
>   * `pacman -Syu` (update stuff)
>   * `pacman -S axyl-xmonad` (got it from here: https://github.com/axyl-os/axyl-iso/wiki/%28FAQ%29How-to-Config:--Themeing%2C-Custom-Adjustment-Modification-Data%2C-Details%2C-and-Other-General-Information-in-FAQ-Format)
>   * `cp -r /etc/skel/.xmonad/ /home/your_user/.xmonad/` (make sure to replace `your_user` with the user you're going to sign in as)
>   * `exit` (this should take you back to the login screen and hopefully display XMonad in the bottom-left menu. if not, try rebooting)
> * Select XMonad in the bottom-left menu and log in.
> 
> I'm barely getting into like Linux stuff so I can't properly explain a lot of it, but glhf.

How would i do this for i3? Please i need to know

**Comment by Kenshin7** [comment]
> How would i do this for i3? Please i need to know i am running this on bare metal i tried install the iso with i3 both with and without auto login but it wont work?

I'm not sure, but try doing `pacman -S axyl-i3wm` instead of `pacman -S axyl-xmonad`

**Comment by Minepool9** [comment]
> > How would i do this for i3? Please i need to know i am running this on bare metal i tried install the iso with i3 both with and without auto login but it wont work?
> 
> I'm not sure, but try doing `pacman -S axyl-i3wm` instead of `pacman -S axyl-xmonad`

what about the cp command? what part would i change?

**Comment by Kenshin7** [comment]
> what about the cp command? what part would i change?

I got that cp command from the end of the output of the pacman -S axyl-xmonad command. Judging from the [FAQ](https://github.com/axyl-os/axyl-iso/wiki/%28FAQ%29How-to-Config:--Themeing%2C-Custom-Adjustment-Modification-Data%2C-Details%2C-and-Other-General-Information-in-FAQ-Format), try running `cp -r /etc/skel/.config/i3 /home/your_user/.config/i3` ?
