### ISSUE TITLE
Unable to set the cursor size system wide

### ISSUE THREAD

**Issue by beyond9thousand** [axyl-os/axyl-iso#77]

**Comment by Shinyzenith** [comment]
`/usr/share/icons/default/index.them`
```
[Icon Theme]
Inherits=macOSBigSur
```

Replace macOSBigSur with your desired icon pack.

Not an axyl bug, closing.

**Comment by beyond9thousand** [comment]
That actually never solved anything and it only sets the theme. Size would not change no matter what I did. Had to switch to a different DM (lightdm)

**Comment by Shinyzenith** [comment]
> That actually never solved anything and it only sets the theme. Size would not change no matter what I did. Had to switch to a different DM (lightdm)

I see, did you try using lxappearance?

**Comment by beyond9thousand** [comment]
Yes, I did. There are things that I did, which worked only partially. For example, I had to set xcursor size in .profile by exporting it
This had fixed the issue, but only inside apps. The cursor would go back to 16 on empty spaces
