### ISSUE TITLE
What is the best way to install another WM alongside the main one?

### ISSUE THREAD

**Issue by ikhlosi** [axyl-os/axyl-iso#79]
I just installed Axyl and loving it so far. In the installer, I have chosen bspwm as WM. However, I would also like to add [Axyl's dwm](https://github.com/axyl-os/axyl-dwm) version. How would I best do this?

Is it a matter of: cloning [the repo](https://github.com/axyl-os/axyl-dwm), building Axyl's dwm as we normally build [vanilla dwm](https://dwm.suckless.org/) and then adding a `dwm.desktop` file in `/usr/share/xsessions`? Would it need any more configuration than that to avoid conflicts with the current bspwm setup?

Thanks in advance for the help.

**Comment by Shinyzenith** [comment]
> I just installed Axyl and loving it so far. In the installer, I have chosen bspwm as WM. However, I would also like to add [Axyl's dwm](https://github.com/axyl-os/axyl-dwm) version. How would I best do this?
> 
> Is it a matter of: cloning [the repo](https://github.com/axyl-os/axyl-dwm), building Axyl's dwm as we normally build [vanilla dwm](https://dwm.suckless.org/) and then adding a `dwm.desktop` file in `/usr/share/xsessions`? Would it need any more configuration than that to avoid conflicts with the current bspwm setup?
> 
> Thanks in advance for the help.

All desktops are packaged into installable packages. run `sudo pacman -Ss axyl-yourwindowmanagerofchoice`

If one shows up, install it, logout and log back into your session of choice.

**Comment by Shinyzenith** [comment]
https://github.com/axyl-os/axyl-repo/tree/master/x86_64 and yes dwm exists if you take a look here.
(pacman -Ss will search through this)
