### ISSUE TITLE
Installation Failed: Package Manager Error

### ISSUE THREAD

**Issue by Kilometres** [axyl-os/axyl-iso#8]
Installation Failed
Package Manager error
The package manager could not prepare updates.
The command

pacman -Sy

returned error code 1

happens after 12-50% of the installer

**Comment by flazz01** [comment]
> Installation Failed Package Manager error The package manager could not prepare updates. The command
> 
> pacman -Sy
> 
> returned error code 1
> 
> happens after 12-50% of the installer

Also happen to me at first time install, but at the second install, its fine. So just restart install from beginning. Should be ok.

**Comment by angelofallars** [comment]
Try rebooting the live ISO install and try again.
