### ISSUE TITLE
Package Manager error ! Installation Failed (The package manager could not prepare updates. The command <pre>pacman</pre> returned error code 1.)

### ISSUE THREAD

**Issue by lknows** [axyl-os/axyl-iso#84]
![Screenshot_2022-06-14-01-19-09_2560x1440](https://user-images.githubusercontent.com/7243001/173661824-db13dbac-6b98-4c4f-841b-30e7dfeae7bd.png)

I can't get around this specific error no matter what combination of selections I make via calamares. I've also double checked no secure boot in BIOS. Have tried both nvidia and x86_64 live boot options.

Is this just something I wait for the next release? Seems similiar to issue#60, but I"m reaching. I'm new. What other info should I have provided?

**Comment by MikeKneeB** [comment]
I'm having the same issue, I've attached my [calamares log](https://gist.github.com/MikeKneeB/ac727b85e5fe58b34b454de53098e1ab). I also tried updating the pacman keyring and mirrorlist:

`sudo pacman -Sy archlinux-keyring pacman-mirrorlist`

No change.

I also tried pinging one of the mirrors that pacman allegedly failed on from the log, and got a response back no problem.

**Comment by dimisc** [comment]
Yeap. Having the same issue. Also tried updating keyring prior to installation. I think a new iso is due.

**Comment by MikeKneeB** [comment]
Yep, `~/.cache/calamares/session.log`.

**Comment by lknows** [comment]
I tried using 2 of the previous .iso's but no joy. I figured I would attach the log file mostly as a learning habit for myself: [v21.11.1 calamares log](https://gist.github.com/lknows/60303bdb9c35e97fec956224f8320842).

**Comment by lknows** [comment]
> `sudo pacman -Sy archlinux-keyring pacman-mirrorlist`
I'm too new to know if this would matter, but I recently tried this before an install and noticed:
`warning: /etc/pacman.d/mirrorlist installed as /etc/pacman.d/mirrorlist.pacnew`
This will probably be my last update pending no other troubleshooting ideas. I have tried every combination of install options from no WM to different partition strats. I also did a garuda install using calamares just to make sure theres no hardware issues in the way on my end, but had 0 issues there.
Thanks all for the support, I'm holding my breath for the new iso. Please let me know if theres anyway I can help/contribute to this dope project!

**Comment by crypt0rabbi** [comment]
I had this same issue with all Window managers , the way i got it to work though was to format my drive then reboot and re run calamares and it worked, this installed the same way on 2 separate pc's. Also once it booted i found when it tries to update there is a issue with libinih and i had to IgnorePkg = libinih in pacman.conf to bypass it

**Comment by lknows** [comment]
> In case all the solutions above don't work for anyone else as well, building the ISO myself finally got it working.

Could you go more in depth? Did you use some tools to build your own iso? I have never built an iso before but am willing to learn

**Comment by lknows** [comment]
I wanted to post that the error has a different appearance, but this is assuredly the same issue as OP

![Screenshot_2022-07-10-04-46-16_2560x1440](https://user-images.githubusercontent.com/7243001/178163194-b7469724-25c8-4934-9557-5c9008f52521.png)

I will be trying @ayowxifu 's solution imminently

**Comment by lknows** [comment]
> > > In case all the solutions above don't work for anyone else as well, building the ISO myself finally got it working.
> > 
> > 
> > Could you go more in depth? Did you use some tools to build your own iso? I have never built an iso before but am willing to learn
> 
> With this one it's actually quite easy. Just clone the repo we're on, build the docker image via `docker build -t axyl-fast` and run the docker-build script, gets you the ISO somewhere in a subfolder. Obviously you can tag the docker image differently too but the script uses axyl-fast so thats just convenience

To be clear, I have finally got a clean install of axyl with most things working as planned.

I wanted to make one last reply to clarify what **MY** specific solution was. I slightly panicked when I couldn't really get docker to work. Can't say what my issue was, I just know after I installed docker and tried the `docker build -t axyl-fast` command I got asked for an additional argument. No worries friends, this part of the suggestion is unnecessary to solve the OP issue at hand.


However after cloning the repo as @ayowxifu suggested, he was fully correct in denoting that running the build.sh which is in the installation-scripts directory, does indeed build you a custom iso that you can use to flash to a USB that will **INDEED WORK**

Atleast it did the trick for me, and I spent quite a bit of time asking people about it lol.
I must consider this closed:D

**Comment by choulth** [comment]
So why not just building a new ISO for everyone to download and use if it is so easy? The last one is from April 1st.

**Comment by lknows** [comment]
> So why not just building a new ISO for everyone to download and use if it is so easy?

Mostly because I'm still experiencing some issues I'd rather not pass on to another user. But as soon as I fix this issue with neovim, I'll see what I can do.
See attached:
![Screenshot_2022-07-10_18:13:28](https://user-images.githubusercontent.com/7243001/178198052-067f788a-2aae-4b7f-aded-9f87357804b4.png)

**Comment by choulth** [comment]
Great, thank you.

**Comment by lknows** [comment]
I was able to fix my neovim issue by changing the home directory name mentioned in the lua error.

I can't host an iso file here as it would be too big, but if anyone else needs an updated iso as a way around a bug or other issue, just pm me for a link.

**Comment by lknows** [comment]
I actually ran into more neovim issues later down the road. 
I was told axyl comes with defaultish(although probably more outdated/old) NvChad settings.

True fix for me was to uninstall/reinstall NvChad using their documentation here: https://nvchad.github.io/quickstart/install

**Comment by lknows** [comment]
> So why not just building a new ISO for everyone to download and use if it is so easy? The last one is from April 1st.

I'm not sure if you still need that updated iso, @choulth  but I'm now hosting one here: https://github.com/lknows/axyl-iso/releases/download/test/axyl-2022.08.10-x86_64.iso

Built it last night, lemme know if it works pls

**Comment by choulth** [comment]
> 

Yeah i do, thank you. Very appreciated.
