### ISSUE TITLE
How to mute notification sounds?

### ISSUE THREAD

**Issue by beyond9thousand** [axyl-os/axyl-iso#85]
Pausing dunst does not mute the notification sounds played by Discord, I was wondering what command I can use to achieve this? I have a custom DND module in my polybar which could make good use of this.

```
#!/bin/bash

# Dunst Notification state
notif=$(dunstctl is-paused)
# echo $notif
file="$HOME/.config/bspwm/polybar/modules.ini"
if [[ $notif = true ]]; then
	dunstctl set-paused false
	polybar-msg hook dunst 1
  # echo entered
	sed -i -e "385s/.*/initial=1/g" "$file"
  # echo "changed value to 2 (toggled off)"
else
	polybar-msg hook dunst 2
	# notify-send "Turned on DND"
	dunstctl set-paused true
	sed -i -e "385s/.*/initial=2/g" "$file"
  # echo "Did not change value to 2 (toggled on)"
  # echo exited
fi
```

**Comment by lknows** [comment]
@beyond9thousand I looked into this issue for a few minutes today. I was curious to know if anything has changed since updating discord?

**Comment by beyond9thousand** [comment]
i mean, that's just discord. i was curious to know if non-DEs had any method to mute notification sounds. When i was on KDE this would always work as expected, regardless of the application

**Comment by beyond9thousand** [comment]
Nice
