### ISSUE TITLE
Switching to Dmenu breaks keybinding

### ISSUE THREAD

**Issue by jaidenleid** [axyl-os/axyl-iso#88]
I just installed the regular dmenu as I prefer it just simple, loading at the top, but 'Super'+D doesn't work with it.  I edited the config.py (I'm running it in Qtile by the way) and it doesn't change anything.  That config file seems to be giving me some trouble here and there actually.
I'd have to suspect that there is a default Axyl configuration going on somewhere that I need to change.  Am I correct?  I can't find anything that points to the Axyl keybindings file here, as far as where it is in the file system.  What am I missing?

Thanks

**Comment by jaidenleid** [comment]
Well after doing a full reboot, my edited config.py is being used and the changes have updated.  I had only been using the MOD+shift+r or MOD+Ctrl+r for resetting the desktop.  This apparently only affected some things. So this is no longer an issue, however, I would still like to know where the default keybindings are located in Axyl if anyone would care to mention.

THANX

**Comment by lknows** [comment]
Axyl uses a hotkey daemon called sxhkd. Config for sxhkd can be found in your `~/.config/sxhkd/sxhkdrc` file.

There is a keybindings.md as well: https://github.com/axyl-os/axyl-iso/blob/master/keybindings.md

Though there doesn't seem to be much info for qtile, so apologies if none of this applies to that wm.
