### ISSUE TITLE
dwm edition installs without dwm

### ISSUE THREAD

**Issue by squidgyberries** [axyl-os/axyl-iso#89]
When I choose to install the dwm edition, dwm doesn't actually get installed which causes a login loop.

**Comment by rncrypto06** [comment]
Any update regarding this issue??

**Comment by lknows** [comment]
@squidgyberries have you tried the build script to create your own updated iso? You can find it in the `installation-scripts` directory here: https://github.com/axyl-os/axyl-iso/tree/master/installation-scripts

I would also try installing i3 or bspwm first so you can try reinstalling `axyl-dwm` don't forget the last step to copy the etc/skel files as well.

**Comment by Peppe61** [comment]
@squidgyberries I can confirm that the latest iso does install dwm (chadwm) properly. Did so last Saturday on bare metal, all worked well. Give it a shot, it is amazing.

**Comment by toha1171** [comment]
> @squidgyberries I can confirm that the latest iso does install dwm (chadwm) properly. Did so last Saturday on bare metal, all worked well. Give it a shot, it is amazing.

Interesting because the newest iso has this issue across DWM and Spectr as well.

**Comment by lknows** [comment]
> > @squidgyberries I can confirm that the latest iso does install dwm (chadwm) properly. Did so last Saturday on bare metal, all worked well. Give it a shot, it is amazing.
> 
> Interesting because the newest iso has this issue across DWM and Spectr as well.

I wanted to transfer a solution that worked for a friend with this issue in DWM specifically (may work for spectrwm but the doubt is real):

1.) `git clone https://github.com/axyl-os/axyl-dwm` 
2.) `cp -r axyl-dwm/etc/skel/.config/dwm ~/.config/dwm`

Hope this helps you good folks! If anyone has more info about the login loop, I can't recreate this personally and don't use dwm much(or ever).

**Comment by lknows** [comment]
@squidgyberries @toha1171 
If either of you good folks can't get results with the plan listed above, could you report any progress or other things you've tried?

**Comment by kobipana** [comment]
i tried the dwm install yesterday (from iso) still login loop, installed i3 afterwards and got dwm working with git clone and skel copy.
It used to work a couple of months ago (my main driver) but unfortunately i had to do a fresh install yesterday..
