### ISSUE TITLE
how to install axyl-nvim again after remove defualt config file by mistake

### ISSUE THREAD

**Issue by modsyan** [axyl-os/axyl-iso#92]
nvim config is still working well in sudo mode

**Comment by lknows** [comment]
Maybe a silly question, but why is `pacman -S axyl-nvim` not a viable solution here?

**Comment by Shinyzenith** [comment]
I'm not too sure but it might be coming from the etc skel of the iso

Also you can just copy It from github

**Comment by modsyan** [comment]
@Shinyzenith  
this is work for me, Thanks a lot 

To any one in future face the same problem
this my solution 
`cp /etc/skel/.config/nvim ~/.config/` & `cp /etc/skel/.local/share/nvim ~/.local/share`
then use `:PackerInstall` and `:PackerCompile`.

note: 
btw reinstalling `axyl-nvim` package didn't work for me idk what the problem with that.
