### ISSUE TITLE
Add monitor in Xmonad

### ISSUE THREAD

**Issue by DoddyJoel** [axyl-os/axyl-iso#93]
Hi, I tried to install axyl-os with Qtile. The installation finished fine, but I noticed that the window manager was not installed. I tried several times to install axyl-os with qtile, and the problem persists so I decided to install xmonad the installation was successful, but now I want to add another monitor. Can you help me how to do this?

**Comment by lknows** [comment]
Have you tried using xrandr or arandr? Are you familiar with these tools?

**Comment by DoddyJoel** [comment]
@lknows  yes, this is the configuration that I have at the moment (**xrandr --output eDP1 --primary --mode 1920x1080 --pos 1366x0 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off --output HDMI-1-0 --mode 1366x768 --pos 0x315 --rotate normal**), but the polybar is not visible on the second screen, how can I add the plolybar to the second screen? . Thank for you answer

**Comment by lknows** [comment]
Have you tried many changes to your polybar config file? For xmonad, I believe you would need to look in the `~/.xmonad/polybar` directory. I would assume trying some simple changes with your `config` file would achieve functional solutions/results.

I would even consider setting `override-redirect` to true, but can't be of much more help as I only have 1 monitor lol

**Comment by DoddyJoel** [comment]
I'm going to close this issue. The solution was to install another windows administrator in my case i3 because the configuration is very easy. I hope they can fix the qtile installation issue. Thank @lknows  for your answer and I hope you are oky.
