### ISSUE TITLE
Can't change cursor shape and behavior

### ISSUE THREAD

**Issue by xenomorphling** [axyl-os/axyl-iso#95]
Can't change cursor shape and behavior, any terminal, any WM. I set cursor shape to Block and blinking off in GUI and in config (alacritty.yml) - no results.

**Comment by lknows** [comment]
I believe `phinger-cursors` is the new default for axyl. Are you having the same issues with the xfce4-terminal? I belive it is also the default for axyl instead of alacritty.

**Comment by xenomorphling** [comment]
Sorry, I'm talking about terminal cursor

**Comment by lknows** [comment]
If you're talking terminal cursor, have you tried tweaking your `.Xresources` file yet?

**Comment by lknows** [comment]
Also, are you sure you're editing the correct alacritty config files? The location of each file is window manager specific. For instance, I use i3, so my `alacritty.yml` isn't stored in my base `.config` directory. Instead, the full path is `~/.config/i3/alacritty/alacritty.yml`

Many users work around this with a symbolic link in `~/.config/` so their terminal looks the same across window managers.

**Comment by xenomorphling** [comment]
I also use i3 and I edit my ~/.config/i3/alacritty/alacritty.yml. Fonts, colors editing works, but I have cursor config:

cursor:
  style:
    shape: Block
    blinking: Off

And it still I-Beam and blinking.

I have no .Xresources in my home directory, what should I do exactly?

**Comment by xenomorphling** [comment]
The same behavior over ssh. I assume something rewrite cursor config independent of terminal client.

**Comment by lknows** [comment]
Set `blinking` to `Never` does function as expected for me, but I easily reproduce the shape persistently defaulting to `Beam` functionality no matter what attribute I enter. I'm looking into it, but don't see any signs of a solution anytime soon from me lool

**Comment by xenomorphling** [comment]
OK, I installed xterm and set in **.Xresources**
xterm*cursorBlink: false
nothing happened, cursor still blinks
but config fonts, like
XTerm*XftFont:                  Segoe UI:size=10:antialias=true:style=Regular
works

**Comment by lknows** [comment]
I can successfully set `unfocused_hollow` to `true` and I do get a nonblinking block cursor, but when I go back to focusing alacritty the `Beam` cursor returns. Partial solution almost lol

**Comment by xenomorphling** [comment]
I completely remove zsh configs and reinstall zsh and now alacritty cursor works as aspected. So I think there is some zsh script which overwrite term configs every time.

**Comment by lknows** [comment]
> I completely remove zsh configs and reinstall zsh and now alacritty cursor works as expected. So I think there is some zsh script which overwrite term configs every time.

You might be right. This was found in my `~/.zshrc-personal`
![Screenshot_2022-08-10_14:52:15](https://user-images.githubusercontent.com/7243001/184007803-b9346ca0-fab4-40bb-a9d2-bf453133fe29.png)

**Comment by ajeshp** [comment]
On Axyl, by default, zsh is using vim mode, which effects the cursor. 
You have to comment out a bunch of stuff in `~/.zshrc-personal` to disable vim mode.

**Comment by lknows** [comment]
> On Axyl, by default, zsh is using vim mode, which effects the cursor. You have to comment out a bunch of stuff in `~/.zshrc-personal` to disable vim mode.

To combine my and @ajeshp's solution, one must comment out lines 90-108 of your base `~/.zshrc-personal` file to disable the default vim mode that takes priority in styling the terminal cursor.

I see no other reason to keep this issue thread open.
