### ISSUE TITLE
Artix iso?

### ISSUE THREAD

**Issue by Devarth123** [axyl-os/axyl-iso#96]
I see few repos on axly artix edition but where do i get the iso from?

**Comment by lknows** [comment]
Have you tried this for the iso?: https://github.com/artix-linux-calamares-installer/alci-iso

And then you could install the axyl packages you want/need later? Not a great/true solution, though.

**Comment by Devarth123** [comment]
Thats not what i asked for, assuming from what u said there is no artix iso for axly so are we gonna ever have a artix iso in releases page?

**Comment by Devarth123** [comment]
Nvm it looks like its in the todo thing
```What To Look Forward To?

   - Axyl will soon have an Artix-based ISO and will use runit as its default init system.
```
