### ISSUE TITLE
White cloudy borders around laptop screen

### ISSUE THREAD

**Issue by Bruskoo** [axyl-os/axyl-iso#98]
How can i fix it?
![IMG_20220817_091651.jpg](https://user-images.githubusercontent.com/93473401/185053066-557c0c93-cae0-4d1f-9ecb-0f9fed6a06c5.jpg)

**Comment by lknows** [comment]
Could you try uploading a '.png' file using the screenshot utility? For most users, the `PrtSc` button will screencap the whole desktop for you. You can also try `Ctrl + PrtSc` to capture the active window. You can also try the screenshot script with `❖ + S` which will bring up a menu to select one of the options already mentioned.

The jpg you uploaded doesn't seem to have any issues other than a bad glare lool

**Comment by lknows** [comment]
@Bruskoo Any updates at all?

If anyone else is having this issue please report, but this seems to me a bit trollish

**Comment by Bruskoo** [comment]
Sorry, forgot to answer, the problem was in the i3 theme settings.
